/**
 * ticketService.ts
 *
 * Dashboard-only service layer for ticket data fetching and mutations.
 * All functions call our own Next.js API routes (not Supabase directly),
 * keeping the data flow: Component → Service → API Route → Supabase.
 *
 * Each function returns the unwrapped data on success or throws a
 * descriptive error, so consumers can handle failures in a single
 * try/catch block or pass the promise to an async thunk.
 */

import type { ApiResponse, Ticket, TicketStatus } from "@/types";

// ── Helpers ──────────────────────────────────────────────────

/**
 * Unwraps an ApiResponse envelope. Throws if the response body
 * contains an error string or if the HTTP status is not ok.
 */
async function unwrapResponse<T>(
  response: Response,
  context: string,
): Promise<T> {
  if (!response.ok) {
    // Attempt to parse a structured error from the body
    let serverMessage: string | null = null;
    try {
      const body = (await response.json()) as ApiResponse<unknown>;
      serverMessage = body.error;
    } catch {
      // Body wasn't JSON — fall through to generic message
    }

    throw new Error(
      serverMessage ?? `${context}: server responded with ${response.status}`,
    );
  }

  const body = (await response.json()) as ApiResponse<T>;

  if (body.error) {
    throw new Error(body.error);
  }

  return body.data as T;
}

// ── Public API ───────────────────────────────────────────────

/**
 * Fetches every ticket from the backend, newest first.
 * Calls GET /api/tickets which falls back to mock data
 * when Supabase credentials are unavailable.
 */
export async function fetchDashboardTickets(): Promise<Ticket[]> {
  const response = await fetch("/api/tickets", {
    method: "GET",
    headers: { "Content-Type": "application/json" },
    // Next.js 15+ uses 'no-store' by default for fetch in client
    // components, but we're explicit to avoid caching stale tickets.
    cache: "no-store",
  });

  return unwrapResponse<Ticket[]>(response, "fetchDashboardTickets");
}

/**
 * Updates a single ticket's status via the dynamic PATCH endpoint.
 * Returns the full updated ticket record.
 */
export async function updateRemoteTicketStatus(
  id: string,
  status: TicketStatus,
): Promise<Ticket> {
  const response = await fetch(`/api/tickets/${encodeURIComponent(id)}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ status }),
  });

  return unwrapResponse<Ticket>(response, "updateRemoteTicketStatus");
}

/**
 * Payload accepted by POST /api/tickets.
 * Mirrors the CreateTicketBody interface in the API route.
 */
export interface CreateTicketPayload {
  customer_email?: string | null;
  message_body: string;
  category: Ticket["category"];
  urgency: Ticket["urgency"];
  ai_draft_reply: string;
  ai_model: string;
}

/**
 * Inserts a new ticket record via POST /api/tickets.
 * Returns the full server-created Ticket (including its UUID
 * and timestamps generated by Supabase).
 *
 * The API route returns 503 when Supabase is unconfigured,
 * so callers should catch and fall back to a client-generated ticket.
 */
export async function createRemoteTicket(
  payload: CreateTicketPayload,
): Promise<Ticket> {
  const response = await fetch("/api/tickets", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  return unwrapResponse<Ticket>(response, "createRemoteTicket");
}
